language: cpp

dist: xenial
sudo: required
osx_image: xcode8.3
cache: ccache

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - TRAVIS_BUILD_TYPE=Debug
  - TRAVIS_BUILD_TYPE=Release

addons:
  apt:
    packages:
      - libassimp-dev
      - libglew-dev
      - libglfw3-dev
      - libglm-dev
      - libopencv-dev
  homebrew:
    packages:
      - ccache
      - eigen
      - assimp
      - glew
      - glm
      - opencv


before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH="/usr/lib/ccache/bin/:$PATH"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - echo "-------------------- BEGIN SYSTEM INFORMATION --------------------"
  - uname -a
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then lsb_release -a; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];   then system_profiler SPSoftwareDataType; fi
  - env
  - which cmake
  - cmake --version
  - which $CC
  - $CC --version
  - which $CXX
  - $CXX --version
  - which ccache
  - ccache --version
  - ccache -s
  - echo "--------------------  END SYSTEM INFORMATION  --------------------"

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/bin/yes | pip2 uninstall numpy || true; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install glfw --HEAD; fi
  - git clone https://github.com/robotology/ycm.git
  - cd ycm
  - git fetch origin pull/214/head:findglew
  - git checkout findglew
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
  - make install
  - export YCM_DIR="$(pwd)/../install/share/YCM/cmake"
  - cd ../..

before_script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..

script:
  - make
  - ctest -N
